apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dump-workspace-task
spec:
  inputs:
    resources:
    - name: gitspace
      type: git
  steps:
  - name: dump-workspace
    image: ubuntu
    command: ["ls"]
    args: ["/workspace/gitspace/"]