apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: rules-branch
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/pwittrock/experimental.git
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dump-workspace-task
spec:
  inputs:
    resources:
      - name: gitspace
        type: git
  steps:
    - name: dump-workspace
      image: ubuntu
      command: ["ls"]
      args: ["/workspace/gitspace/"]