apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: dev-deploy-image-
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    # Push dev environment
    tekctl.tektoncd.dev/match: "refs/heads/deploy-dev"
spec:
  taskSpec:
    serviceAccount: tekctl
    inputs:
      resources:
      - name: gitspace
        type: git
      - name: gssecrets
        type: storage
        targetPath: "gitspace/config/bases/token2"
    steps:
    - name: apply
      image: gcr.io/pwittrock-dev/kubectl
      command:
        - kubectl
      args:
        - "apply"
        - "-k=/workspace/gitspace/config/deploy-dev/us-west"
    - name: wait
      image: ubuntu
      command:
        - "sleep"
      args:
        - "10000"
  inputs:
    resources:
    - name: gitspace
      resourceSpec:
        type: git
        params:
          - name: revision
            value: "{{ .Ref }}"
          - name: url
            value: https://github.com/pwittrock/experimental
    - name: gssecrets
      resourceSpec:
        type: storage
        params:
          - name: type
            value: gcs
          - name: location
            value: gs://pwittrock-dev/token
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: prod-deploy-image-
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    # Push prod environment
    tekctl.tektoncd.dev/match: "refs/heads/deploy-prod"
spec:
  taskSpec:
    serviceAccount: tekctl
    inputs:
      resources:
      - name: gitspace
        type: git
        targetPath: "/workspace/gitspace/"
      - name: gssecrets
        type: storage
        targetPath: "/workspace/gitspace/config/bases/"
    steps:
    - name: apply
      image: gcr.io/pwittrock-dev/kubectl
      command:
        - kubectl
      args:
        - "apply"
        - "-k=/workspace/gitspace/config/deploy-prod/us-west"
  inputs:
    resources:
    - name: gitspace
      resourceSpec:
        type: git
        params:
          - name: revision
            value: "{{ .Ref }}"
          - name: url
            value: https://github.com/pwittrock/experimental
    - name: gssecrets
      resourceSpec:
        type: storage
        params:
          - name: type
            value: gcs
          - name: location
            value: gs://pwittrock-dev
