---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-git-branch-a-
  annotations:
    tekctl.tektoncd.dev/trigger: "push"
spec:
  inputs:
    resources:
    - name: gitspace
      resourceSpec:
        type: git
        params:
          - name: revision
            value: {{.Ref}}
          - name: url
            value: {{.URL}}
  outputs:
    resources:
    - name: builtImage
      resourceSpec:
        type: image
        params:
        - name: url
          value: gcr.io/pwittrock-dev/tekctl
  taskRef:
    name: build-image-task
