apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: build-image-
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    tekctl.tektoncd.dev/push-types: "tag"
spec:
  inputs:
    resources:
    - name: gitspace
      resourceSpec:
        type: git
        params:
          - name: revision
            value: {{ .Tag }}
          - name: url
            value: https://github.com/pwittrock/tekctl
  outputs:
    resources:
    - name: builtImage
      resourceSpec:
        type: image
        params:
        - name: url
          value: gcr.io/pwittrock-dev/tekctl:{{ .Tag }}
  taskRef:
    name: build-image
---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: deploy-image-
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    tekctl.tektoncd.dev/push-types: "branch"
spec:
  inputs:
    resources:
      - name: gitspace
        resourceSpec:
          type: git
          params:
            - name: revision
              value: {{ .Branch }}
            - name: url
              value: https://github.com/pwittrock/tekctl
  taskRef:
    name: deploy-image
