// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package triggers

import (
	"tektoncd.dev/experimental/pkg/wirecli/wiregithub"
)

// Injectors from wire.go:

func InitializeTrigger() (*GitHubEventMonitor, error) {
	gitHubWebHookSecret := wiregithub.NewGitHubWebHookSecret()
	gitHubEventMonitor := &GitHubEventMonitor{
		Secret: gitHubWebHookSecret,
	}
	return gitHubEventMonitor, nil
}
