// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package triggers

import (
	"tektoncd.dev/experimental/pkg/wirecli/wiregithub"
)

// Injectors from wire.go:

func InitializeTrigger() (*GitHubEventMonitor, error) {
	gitHubWebHookSecretPath := wiregithub.NewGitHubWebHookSecretPath()
	gitHubWebHookSecret, err := wiregithub.NewGitHubWebHookSecret(gitHubWebHookSecretPath)
	if err != nil {
		return nil, err
	}
	gitHubTokenPath := wiregithub.NewGitHubTokenPath()
	gitHubToken, err := wiregithub.NewGitHubToken(gitHubTokenPath)
	if err != nil {
		return nil, err
	}
	gitHubEventMonitor := &GitHubEventMonitor{
		Secret: gitHubWebHookSecret,
		Token:  gitHubToken,
	}
	return gitHubEventMonitor, nil
}
