apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-image-task
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    tekctl.tektoncd.dev/match: "refs/heads/tekton"
spec:
  steps:
    - name: apply
      image: gcr.io/pwittrock-dev/kubectl
      command: ['kubectl']
      args: ['apply', '-k=${inputs.params.pathToConfig}']
  inputs:
    params:
      - name: pathToConfig
        description: The path to the dockerfile to build
        default: /workspace/gitspace/config
    resources:
      - name: gitspace
        type: git
      - name: gssecrets
        type: storage
        targetPath: "gitspace/config/bases/"