apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: dump-workspace-task
spec:
  inputs:
    resources:
    - name: gitspace
      type: git
  steps:
  - name: dump-workspace
    image: ubuntu
    command: ["ls"]
    args: ["/workspace/gitspace/tekton/apply"]
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    command:
      - /kaniko/executor
    args:
      - --dockerfile=/workspace/gitspace/Dockerfile
      - --destination=gcr.io/pwittrock-dev/tekctl
      - --context=/workspace/gitspace/