apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-image
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    tekctl.tektoncd.dev/push-types: "branch"
    tekctl.tektoncd.dev/push-branches: "tekctl"
spec:
  inputs:
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/gitspace/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default: /workspace/gitspace/
    resources:
      - name: gitspace
        type: git
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    command:
      - /kaniko/executor
    args:
      - --dockerfile=${inputs.params.pathToDockerFile}
      - --destination=${outputs.resources.builtImage.url}
      - --context=${inputs.params.pathToContext}
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-image
  annotations:
    tekctl.tektoncd.dev/triggers: "push"
    tekctl.tektoncd.dev/push-types: "branch"
    tekctl.tektoncd.dev/push-branches: "tekctl"
spec:
  inputs:
    resources:
      - name: gitspace
        type: git
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello world"