---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: test-git-branch
  annotations:
    tekctl.tektoncd.dev/trigger: "push"
spec:
  inputs:
    resources:
      - name: gitspace
        resourceRef:
          name: rules-branch
  taskRef:
    name: dump-workspace-task
